/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Threading.Tasks;
using ProjectNameNorthwind.Mvc.SampleViewModels;
using ProjectNameNorthwind.Business;
using ProjectNameNorthwind.Business.Interfaces;
using ProjectNameNorthwind.Business.Repository;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Mvc.SampleApiControllers
{
	public partial class OrderController : ApiController
	{
		protected IOrderRepository _iOrderRepository;

            // GET: api/Order
        public async Task<IHttpActionResult> GetOrder(int page = 0, int pageSize = 5)
        {
            int totalCount = 0;

            IList<OrderVm> listVm = new List<OrderVm>();
            var result = Task.Factory.StartNew(() => {

                ICriteria criteria = new Criteria<BOOrder>(OrderRepository);
                totalCount = criteria.Count();

                IList<BOOrder> listBOs = criteria
                    .Add(new OrderBy("Id", OrderBy.OrderDirection.Ascending))
                    .Skip(page * pageSize)
                    .Take(pageSize)
                    .List<BOOrder>();

                foreach (var bo in listBOs)
                    listVm.Add(new OrderVm(bo));
                return listVm;
            });
            await result;

            return Ok(new { Data = result.Result, Paging = new { Total = totalCount, Limit = pageSize, CurrentPage = page, PageCount = (int) Math.Ceiling((double)totalCount / pageSize) } });
        }

        // GET: api/Order/5
        [ResponseType(typeof(OrderVm))]
        public async Task<IHttpActionResult> GetOrder(Int32 id)
        {
            var result = Task.Factory.StartNew(() => {

                BOOrder bo = new Criteria<BOOrder>(OrderRepository)
                .Add(Expression.Eq("Id", id))
                .SingleOrDefault<BOOrder>();
                return bo == null ? null : new OrderVm(bo);

            });
            await result;
            if (result.Result == null)
            {
                return NotFound();
            }

            return Ok(result.Result);
        }

        // PUT: api/Order/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutOrder(Int32 id, OrderVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != vm.Id)
            {
                return BadRequest();
            }

            var result = Task.Factory.StartNew(() => {

                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { OrderRepository }); 
                var bo = (BOOrder)vm.BOOrder(OrderRepository);
                uow.Update(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Order
        [ResponseType(typeof(OrderVm))]
        public async Task<IHttpActionResult> PostOrder(OrderVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = Task.Factory.StartNew(() =>
            {
                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { OrderRepository }); 
                var bo = (BOOrder)vm.BOOrder(OrderRepository);
                uow.Create(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                vm = new OrderVm(bo);
                return true;
            });
            await result;
            return CreatedAtRoute("DefaultApi", new { id = vm.Id }, vm);
        }

        // DELETE: api/Order/5
        [ResponseType(typeof(OrderVm))]
        public async Task<IHttpActionResult> DeleteOrder(Int32 id)
        {
            var result = Task.Factory.StartNew(() =>
            {
                 IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { OrderRepository }); 
                var bo = new BOOrder();
                bo.Repository = OrderRepository;
                bo.Init(id);
                
                uow.Delete(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return Ok(result.Result);
        }

        
        public IOrderRepository OrderRepository
        {
            get { return _iOrderRepository ?? (_iOrderRepository = RF.New().OrderRepository); }
            set { _iOrderRepository = value; }
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
	}
}
