/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Threading.Tasks;
using ProjectNameNorthwind.Mvc.SampleViewModels;
using ProjectNameNorthwind.Business;
using ProjectNameNorthwind.Business.Interfaces;
using ProjectNameNorthwind.Business.Repository;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Mvc.SampleApiControllers
{
	public partial class ProductController : ApiController
	{
		protected IProductRepository _iProductRepository;

            // GET: api/Product
        public async Task<IHttpActionResult> GetProduct(int page = 0, int pageSize = 5)
        {
            int totalCount = 0;

            IList<ProductVm> listVm = new List<ProductVm>();
            var result = Task.Factory.StartNew(() => {

                ICriteria criteria = new Criteria<BOProduct>(ProductRepository);
                totalCount = criteria.Count();

                IList<BOProduct> listBOs = criteria
                    .Add(new OrderBy("Id", OrderBy.OrderDirection.Ascending))
                    .Skip(page * pageSize)
                    .Take(pageSize)
                    .List<BOProduct>();

                foreach (var bo in listBOs)
                    listVm.Add(new ProductVm(bo));
                return listVm;
            });
            await result;

            return Ok(new { Data = result.Result, Paging = new { Total = totalCount, Limit = pageSize, CurrentPage = page, PageCount = (int) Math.Ceiling((double)totalCount / pageSize) } });
        }

        // GET: api/Product/5
        [ResponseType(typeof(ProductVm))]
        public async Task<IHttpActionResult> GetProduct(Int32 id)
        {
            var result = Task.Factory.StartNew(() => {

                BOProduct bo = new Criteria<BOProduct>(ProductRepository)
                .Add(Expression.Eq("Id", id))
                .SingleOrDefault<BOProduct>();
                return bo == null ? null : new ProductVm(bo);

            });
            await result;
            if (result.Result == null)
            {
                return NotFound();
            }

            return Ok(result.Result);
        }

        // PUT: api/Product/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutProduct(Int32 id, ProductVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != vm.Id)
            {
                return BadRequest();
            }

            var result = Task.Factory.StartNew(() => {

                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { ProductRepository }); 
                var bo = (BOProduct)vm.BOProduct(ProductRepository);
                uow.Update(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Product
        [ResponseType(typeof(ProductVm))]
        public async Task<IHttpActionResult> PostProduct(ProductVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = Task.Factory.StartNew(() =>
            {
                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { ProductRepository }); 
                var bo = (BOProduct)vm.BOProduct(ProductRepository);
                uow.Create(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                vm = new ProductVm(bo);
                return true;
            });
            await result;
            return CreatedAtRoute("DefaultApi", new { id = vm.Id }, vm);
        }

        // DELETE: api/Product/5
        [ResponseType(typeof(ProductVm))]
        public async Task<IHttpActionResult> DeleteProduct(Int32 id)
        {
            var result = Task.Factory.StartNew(() =>
            {
                 IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { ProductRepository }); 
                var bo = new BOProduct();
                bo.Repository = ProductRepository;
                bo.Init(id);
                
                uow.Delete(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return Ok(result.Result);
        }

        
        public IProductRepository ProductRepository
        {
            get { return _iProductRepository ?? (_iProductRepository = RF.New().ProductRepository); }
            set { _iProductRepository = value; }
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
	}
}
