/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using System.Threading.Tasks;
using ProjectNameNorthwind.Mvc.SampleViewModels;
using ProjectNameNorthwind.Business;
using ProjectNameNorthwind.Business.Interfaces;
using ProjectNameNorthwind.Business.Repository;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Mvc.SampleApiControllers
{
	public partial class SupplierController : ApiController
	{
		protected ISupplierRepository _iSupplierRepository;

            // GET: api/Supplier
        public async Task<IHttpActionResult> GetSupplier(int page = 0, int pageSize = 5)
        {
            int totalCount = 0;

            IList<SupplierVm> listVm = new List<SupplierVm>();
            var result = Task.Factory.StartNew(() => {

                ICriteria criteria = new Criteria<BOSupplier>(SupplierRepository);
                totalCount = criteria.Count();

                IList<BOSupplier> listBOs = criteria
                    .Add(new OrderBy("Id", OrderBy.OrderDirection.Ascending))
                    .Skip(page * pageSize)
                    .Take(pageSize)
                    .List<BOSupplier>();

                foreach (var bo in listBOs)
                    listVm.Add(new SupplierVm(bo));
                return listVm;
            });
            await result;

            return Ok(new { Data = result.Result, Paging = new { Total = totalCount, Limit = pageSize, CurrentPage = page, PageCount = (int) Math.Ceiling((double)totalCount / pageSize) } });
        }

        // GET: api/Supplier/5
        [ResponseType(typeof(SupplierVm))]
        public async Task<IHttpActionResult> GetSupplier(Int32 id)
        {
            var result = Task.Factory.StartNew(() => {

                BOSupplier bo = new Criteria<BOSupplier>(SupplierRepository)
                .Add(Expression.Eq("Id", id))
                .SingleOrDefault<BOSupplier>();
                return bo == null ? null : new SupplierVm(bo);

            });
            await result;
            if (result.Result == null)
            {
                return NotFound();
            }

            return Ok(result.Result);
        }

        // PUT: api/Supplier/5
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutSupplier(Int32 id, SupplierVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != vm.Id)
            {
                return BadRequest();
            }

            var result = Task.Factory.StartNew(() => {

                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { SupplierRepository }); 
                var bo = (BOSupplier)vm.BOSupplier(SupplierRepository);
                uow.Update(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Supplier
        [ResponseType(typeof(SupplierVm))]
        public async Task<IHttpActionResult> PostSupplier(SupplierVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var result = Task.Factory.StartNew(() =>
            {
                IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { SupplierRepository }); 
                var bo = (BOSupplier)vm.BOSupplier(SupplierRepository);
                uow.Create(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                vm = new SupplierVm(bo);
                return true;
            });
            await result;
            return CreatedAtRoute("DefaultApi", new { id = vm.Id }, vm);
        }

        // DELETE: api/Supplier/5
        [ResponseType(typeof(SupplierVm))]
        public async Task<IHttpActionResult> DeleteSupplier(Int32 id)
        {
            var result = Task.Factory.StartNew(() =>
            {
                 IUnitOfWork uow = new UnitOfWorkImp(new IRepositoryConnection[] { SupplierRepository }); 
                var bo = new BOSupplier();
                bo.Repository = SupplierRepository;
                bo.Init(id);
                
                uow.Delete(bo);

                string err;
                if (!uow.Commit(out err))
                {
                    var resp = new HttpResponseMessage(HttpStatusCode.BadRequest) { Content = new StringContent(err) };
                    throw new HttpResponseException(resp);
                }
                return true;
            });
            await result;
            if (!result.Result)
                return NotFound();

            return Ok(result.Result);
        }

        
        public ISupplierRepository SupplierRepository
        {
            get { return _iSupplierRepository ?? (_iSupplierRepository = RF.New().SupplierRepository); }
            set { _iSupplierRepository = value; }
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
	}
}
