USE [Northwind]
GO

------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 5/6/2019 1:07:04 PM
------------------------------------------------------------
-- schema entity update to support concurrency management
IF COL_LENGTH('dbo.Customer', 'ctr_version') IS NULL
ALTER TABLE [dbo].[Customer]  ADD ctr_version INT DEFAULT 0 NOT NULL
GO
---------------------------------------------------------


------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 5/6/2019 1:07:04 PM
------------------------------------------------------------
-- schema entity update to support concurrency management
IF COL_LENGTH('dbo.Order', 'ctr_version') IS NULL
ALTER TABLE [dbo].[Order]  ADD ctr_version INT DEFAULT 0 NOT NULL
GO
---------------------------------------------------------


------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 5/6/2019 1:07:04 PM
------------------------------------------------------------
-- schema entity update to support concurrency management
IF COL_LENGTH('dbo.OrderItem', 'ctr_version') IS NULL
ALTER TABLE [dbo].[OrderItem]  ADD ctr_version INT DEFAULT 0 NOT NULL
GO
---------------------------------------------------------


------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 5/6/2019 1:07:04 PM
------------------------------------------------------------
-- schema entity update to support concurrency management
IF COL_LENGTH('dbo.Product', 'ctr_version') IS NULL
ALTER TABLE [dbo].[Product]  ADD ctr_version INT DEFAULT 0 NOT NULL
GO
---------------------------------------------------------


------------------------------------------------------------
-- Stored procedure generated by CodeTrigger
-- This script was generated on 5/6/2019 1:07:04 PM
------------------------------------------------------------
-- schema entity update to support concurrency management
IF COL_LENGTH('dbo.Supplier', 'ctr_version') IS NULL
ALTER TABLE [dbo].[Supplier]  ADD ctr_version INT DEFAULT 0 NOT NULL
GO
---------------------------------------------------------


