/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using ProjectNameNorthwind.Data;
using ProjectNameNorthwind.Data.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Business.Repository
{
	///<Summary>
	///Class definition
	///This is the definition of the OrderItemRepository.
	///</Summary>
	public partial class OrderItemRepository : IOrderItemRepository, IDisposable
	{
		#region member variables
		IConnectionProvider _connectionProvider;
		bool _isDisposed = false;
		#endregion

		#region disposable interface support
		public void Dispose()
		{
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		protected virtual void Dispose(bool isDisposing)
		{
			if(!_isDisposed)
			{
				if(isDisposing)
				{
					if(_connectionProvider != null)
					{
						((IDisposable)_connectionProvider).Dispose();
						_connectionProvider = null;
					}
				}
			}
			_isDisposed = true;
		}
		#endregion

		#region methods
		public virtual IBaseData BaseData(IDAOOrderItem daoOrderItem)
		{	return (IBaseData)(DAOOrderItem)daoOrderItem;	}

		public virtual IDAOOrderItem New()
		{	return new DAOOrderItem();	}

		public virtual void Insert(IDAOOrderItem daoOrderItem)
		{	daoOrderItem.Insert();	}

		public virtual void Update(IDAOOrderItem daoOrderItem)
		{	daoOrderItem.Update();	}

		public virtual void Delete(IDAOOrderItem daoOrderItem)
		{	daoOrderItem.Delete();	}

		public virtual IList<IDAOOrderItem> SelectAll()
		{	return DAOOrderItem.SelectAll();	}

		public virtual Int32 SelectAllCount()
		{	return DAOOrderItem.SelectAllCount();	}

		public virtual IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{	return DAOOrderItem.SelectAllByCriteriaProjection(listProjection, listCriterion, listOrder, dataSkip, dataTake);	}

		public virtual IList<IDAOOrderItem> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{	return DAOOrderItem.SelectAllByCriteria(listCriterion, listOrder, dataSkip, dataTake);	}

		public virtual Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{	return DAOOrderItem.SelectAllByCriteriaCount(listCriterion);	}

		public virtual IDAOOrderItem SelectOne(Int32? id)
		{	return DAOOrderItem.SelectOne(id);	}

		public virtual IList<IDAOOrderItem> SelectAllByOrderId(Int32? orderId)
		{	return DAOOrderItem.SelectAllByOrderId(orderId);	}

		public virtual void DeleteAllByOrderId(Int32? orderId)
		{	DAOOrderItem.DeleteAllByOrderId(ConnectionProvider, orderId);	}

		public virtual IList<IDAOOrderItem> SelectAllByProductId(Int32? productId)
		{	return DAOOrderItem.SelectAllByProductId(productId);	}

		public virtual void DeleteAllByProductId(Int32? productId)
		{	DAOOrderItem.DeleteAllByProductId(ConnectionProvider, productId);	}

		#endregion

		#region properties
		public virtual IConnectionProvider ConnectionProvider
		{
			get { return _connectionProvider; }
			set { _connectionProvider = value; }
		}

		#endregion

	}
}
