/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using ProjectNameNorthwind.Data;
using ProjectNameNorthwind.Data.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Business.Repository
{
	///<Summary>
	///Class definition
	///This is the definition of the ProductRepository.
	///</Summary>
	public partial class ProductRepository : IProductRepository, IDisposable
	{
		#region member variables
		IConnectionProvider _connectionProvider;
		bool _isDisposed = false;
		#endregion

		#region disposable interface support
		public void Dispose()
		{
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		protected virtual void Dispose(bool isDisposing)
		{
			if(!_isDisposed)
			{
				if(isDisposing)
				{
					if(_connectionProvider != null)
					{
						((IDisposable)_connectionProvider).Dispose();
						_connectionProvider = null;
					}
				}
			}
			_isDisposed = true;
		}
		#endregion

		#region methods
		public virtual IBaseData BaseData(IDAOProduct daoProduct)
		{	return (IBaseData)(DAOProduct)daoProduct;	}

		public virtual IDAOProduct New()
		{	return new DAOProduct();	}

		public virtual void Insert(IDAOProduct daoProduct)
		{	daoProduct.Insert();	}

		public virtual void Update(IDAOProduct daoProduct)
		{	daoProduct.Update();	}

		public virtual void Delete(IDAOProduct daoProduct)
		{	daoProduct.Delete();	}

		public virtual IList<IDAOProduct> SelectAll()
		{	return DAOProduct.SelectAll();	}

		public virtual Int32 SelectAllCount()
		{	return DAOProduct.SelectAllCount();	}

		public virtual IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{	return DAOProduct.SelectAllByCriteriaProjection(listProjection, listCriterion, listOrder, dataSkip, dataTake);	}

		public virtual IList<IDAOProduct> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{	return DAOProduct.SelectAllByCriteria(listCriterion, listOrder, dataSkip, dataTake);	}

		public virtual Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{	return DAOProduct.SelectAllByCriteriaCount(listCriterion);	}

		public virtual IDAOProduct SelectOne(Int32? id)
		{	return DAOProduct.SelectOne(id);	}

		public virtual IList<IDAOProduct> SelectAllBySupplierId(Int32? supplierId)
		{	return DAOProduct.SelectAllBySupplierId(supplierId);	}

		public virtual void DeleteAllBySupplierId(Int32? supplierId)
		{	DAOProduct.DeleteAllBySupplierId(ConnectionProvider, supplierId);	}

		#endregion

		#region properties
		public virtual IConnectionProvider ConnectionProvider
		{
			get { return _connectionProvider; }
			set { _connectionProvider = value; }
		}

		#endregion

	}
}
