/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using ProjectNameNorthwind.Data;
using ProjectNameNorthwind.Data.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Business.Repository
{
	///<Summary>
	///Class definition
	///This is the definition of the SupplierRepository.
	///</Summary>
	public partial class SupplierRepository : ISupplierRepository, IDisposable
	{
		#region member variables
		IConnectionProvider _connectionProvider;
		bool _isDisposed = false;
		#endregion

		#region disposable interface support
		public void Dispose()
		{
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		protected virtual void Dispose(bool isDisposing)
		{
			if(!_isDisposed)
			{
				if(isDisposing)
				{
					if(_connectionProvider != null)
					{
						((IDisposable)_connectionProvider).Dispose();
						_connectionProvider = null;
					}
				}
			}
			_isDisposed = true;
		}
		#endregion

		#region methods
		public virtual IBaseData BaseData(IDAOSupplier daoSupplier)
		{	return (IBaseData)(DAOSupplier)daoSupplier;	}

		public virtual IDAOSupplier New()
		{	return new DAOSupplier();	}

		public virtual void Insert(IDAOSupplier daoSupplier)
		{	daoSupplier.Insert();	}

		public virtual void Update(IDAOSupplier daoSupplier)
		{	daoSupplier.Update();	}

		public virtual void Delete(IDAOSupplier daoSupplier)
		{	daoSupplier.Delete();	}

		public virtual IList<IDAOSupplier> SelectAll()
		{	return DAOSupplier.SelectAll();	}

		public virtual Int32 SelectAllCount()
		{	return DAOSupplier.SelectAllCount();	}

		public virtual IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{	return DAOSupplier.SelectAllByCriteriaProjection(listProjection, listCriterion, listOrder, dataSkip, dataTake);	}

		public virtual IList<IDAOSupplier> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{	return DAOSupplier.SelectAllByCriteria(listCriterion, listOrder, dataSkip, dataTake);	}

		public virtual Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{	return DAOSupplier.SelectAllByCriteriaCount(listCriterion);	}

		public virtual IDAOSupplier SelectOne(Int32? id)
		{	return DAOSupplier.SelectOne(id);	}

		#endregion

		#region properties
		public virtual IConnectionProvider ConnectionProvider
		{
			get { return _connectionProvider; }
			set { _connectionProvider = value; }
		}

		#endregion

	}
}
