/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using ProjectNameNorthwind.Business;
using ProjectNameNorthwind.Business.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Mvc.SampleViewModels
{
	public partial class CustomerVm
	{
		#region member properties
		
		public virtual Int32? Id { get; set;}
		
		public virtual string FirstName { get; set;}
		
		public virtual string LastName { get; set;}
		
		public virtual string City { get; set;}
		
		public virtual string Country { get; set;}
		
		public virtual string Phone { get; set;}
		#endregion
		
		public CustomerVm() {}
		
		public CustomerVm(IBOCustomer boCustomer)
		{
			Id = boCustomer.Id;
			FirstName = boCustomer.FirstName;
			LastName = boCustomer.LastName;
			City = boCustomer.City;
			Country = boCustomer.Country;
			Phone = boCustomer.Phone;
		}
		
		public IBOCustomer BOCustomer()
		{
			var boCustomer = new BOCustomer()
			{
				Id = this.Id,
				FirstName = this.FirstName,
				LastName = this.LastName,
				City = this.City,
				Country = this.Country,
				Phone = this.Phone
			};
			return boCustomer;
		}
		
		public IBOCustomer BOCustomer(ICustomerRepository repo)
		{
			BOCustomer boCustomer = (BOCustomer)BOCustomer();
			boCustomer.Repository = repo;
			return boCustomer;
		}
	}
}
