/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using ProjectNameNorthwind.Business;
using ProjectNameNorthwind.Business.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Mvc.SampleViewModels
{
	public partial class OrderItemVm
	{
		#region member properties
		
		public virtual Int32? Id { get; set;}
		
		public virtual Int32? OrderId { get; set;}
		
		public virtual Int32? ProductId { get; set;}
		
		public virtual decimal? UnitPrice { get; set;}
		
		public virtual Int32? Quantity { get; set;}
		#endregion
		
		public OrderItemVm() {}
		
		public OrderItemVm(IBOOrderItem boOrderItem)
		{
			Id = boOrderItem.Id;
			OrderId = boOrderItem.OrderId;
			ProductId = boOrderItem.ProductId;
			UnitPrice = boOrderItem.UnitPrice;
			Quantity = boOrderItem.Quantity;
		}
		
		public IBOOrderItem BOOrderItem()
		{
			var boOrderItem = new BOOrderItem()
			{
				Id = this.Id,
				OrderId = this.OrderId,
				ProductId = this.ProductId,
				UnitPrice = this.UnitPrice,
				Quantity = this.Quantity
			};
			return boOrderItem;
		}
		
		public IBOOrderItem BOOrderItem(IOrderItemRepository repo)
		{
			BOOrderItem boOrderItem = (BOOrderItem)BOOrderItem();
			boOrderItem.Repository = repo;
			return boOrderItem;
		}
	}
}
