/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using ProjectNameNorthwind.Business;
using ProjectNameNorthwind.Business.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Mvc.SampleViewModels
{
	public partial class OrderVm
	{
		#region member properties
		
		public virtual Int32? Id { get; set;}
		
		public virtual DateTime? OrderDate { get; set;}
		
		public virtual string OrderNumber { get; set;}
		
		public virtual Int32? CustomerId { get; set;}
		
		public virtual decimal? TotalAmount { get; set;}
		#endregion
		
		public OrderVm() {}
		
		public OrderVm(IBOOrder boOrder)
		{
			Id = boOrder.Id;
			OrderDate = boOrder.OrderDate;
			OrderNumber = boOrder.OrderNumber;
			CustomerId = boOrder.CustomerId;
			TotalAmount = boOrder.TotalAmount;
		}
		
		public IBOOrder BOOrder()
		{
			var boOrder = new BOOrder()
			{
				Id = this.Id,
				OrderDate = this.OrderDate,
				OrderNumber = this.OrderNumber,
				CustomerId = this.CustomerId,
				TotalAmount = this.TotalAmount
			};
			return boOrder;
		}
		
		public IBOOrder BOOrder(IOrderRepository repo)
		{
			BOOrder boOrder = (BOOrder)BOOrder();
			boOrder.Repository = repo;
			return boOrder;
		}
	}
}
