/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using ProjectNameNorthwind.Business;
using ProjectNameNorthwind.Business.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Mvc.SampleViewModels
{
	public partial class ProductVm
	{
		#region member properties
		
		public virtual Int32? Id { get; set;}
		
		public virtual string ProductName { get; set;}
		
		public virtual Int32? SupplierId { get; set;}
		
		public virtual decimal? UnitPrice { get; set;}
		
		public virtual string Package { get; set;}
		
		public virtual bool? IsDiscontinued { get; set;}
		#endregion
		
		public ProductVm() {}
		
		public ProductVm(IBOProduct boProduct)
		{
			Id = boProduct.Id;
			ProductName = boProduct.ProductName;
			SupplierId = boProduct.SupplierId;
			UnitPrice = boProduct.UnitPrice;
			Package = boProduct.Package;
			IsDiscontinued = boProduct.IsDiscontinued;
		}
		
		public IBOProduct BOProduct()
		{
			var boProduct = new BOProduct()
			{
				Id = this.Id,
				ProductName = this.ProductName,
				SupplierId = this.SupplierId,
				UnitPrice = this.UnitPrice,
				Package = this.Package,
				IsDiscontinued = this.IsDiscontinued
			};
			return boProduct;
		}
		
		public IBOProduct BOProduct(IProductRepository repo)
		{
			BOProduct boProduct = (BOProduct)BOProduct();
			boProduct.Repository = repo;
			return boProduct;
		}
	}
}
