/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
**************************************************************/

using System;

namespace ProjectNameNorthwind.Data.Interfaces
{
    //IzProjectNameNorthwindConn_BaseData
    public partial interface IBaseData
	{
		IConnectionProvider ConnectionProvider	{	set;	}
	}
}
