/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;

namespace ProjectNameNorthwind.Data.Interfaces
{
	public partial interface IDAOOrderItem 
	{
		#region class methods

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table OrderItem based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void Delete();







		///<Summary>
		///Insert a new row
		///This method saves a new object to the table OrderItem
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void Insert();






		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table OrderItem based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void Update();

		#endregion

		#region member properties

		Int32? Id	{	get;	set;	}
		
		Int32? OrderId	{	get;	set;	}
		
		Int32? ProductId	{	get;	set;	}
		
		decimal? UnitPrice	{	get;	set;	}
		
		Int32? Quantity	{	get;	set;	}
		
		Int32? CtrVersion	{	get;	set;	}
		
		#endregion
	}
}
