/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
**************************************************************/

using System;

namespace ProjectNameNorthwind.Data.Interfaces
{
	public interface IDataCriterion
	{
		string ToSql();
	}

	public interface IDataOrderBy
	{
		string ToSql();
	}

	public interface IDataSkip
	{
		string ToSql();
	}

	public interface IDataTake
	{
		string ToSql();
	}

	public interface IDataProjection
	{
		string Member { get; set; }
		string ToSql();
	}

}
