/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
**************************************************************/

using System;
using ProjectNameNorthwind.Data;
using ProjectNameNorthwind.Data.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Business.Interfaces
{
    //IzProjectNameNorthwindConn_BaseBusiness
    public partial interface IBaseBusiness
	{
		void BeginTransactions(IRepositoryConnection[] repos, string trans);
		void BeginTransaction(IRepositoryConnection repo, string trans);
		void RollbackTransactions(IRepositoryConnection[] repos, string trans);
		void RollbackTransaction(IRepositoryConnection repo, string trans);
		void CommitTransactions(IRepositoryConnection[] repo);
		void CommitTransaction(IRepositoryConnection repo);
	}
}
