/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using ProjectNameNorthwind.Data.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Business.Interfaces
{
	///<Summary>
	///Interface definition
	///This is the interface definition for the class BOCustomer.
	///</Summary>
	public partial interface IBOCustomer 
	{
		#region class methods
		
		///<Summary>
		///SaveNew
		///This method persists a new Customer record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void SaveNew();
		
		///<Summary>
		///Update
		///This method updates one Customer record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOCustomer
		///</parameters>
		void Update();
		
		///<Summary>
		///Delete
		///This method deletes one Customer record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void Delete();
		
		///<Summary>
		///OrderCollection
		///This method returns its collection of BOOrder objects
		///</Summary>
		///<returns>
		///IList[IBOOrder]
		///</returns>
		///<parameters>
		///BOCustomer
		///</parameters>
		IList<IBOOrder> OrderCollection();
		
		///<Summary>
		///LoadOrderCollection
		///This method loads the internal collection of BOOrder objects from storage. 
		///Call this if you need to ensure the collection is up-to-date (concurrency)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void LoadOrderCollection();
		
		///<Summary>
		///AddOrder
		///This method persists a BOOrder object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOOrder
		///</parameters>
		void AddOrder(IBOOrder boOrder);
		
		///<Summary>
		///DeleteAllOrder
		///This method deletes all BOOrder objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void DeleteAllOrder();
		
		#endregion

		#region member properties
		
		ICustomerRepository CustomerRepository	{	set;}
		
		IOrderRepository OrderRepository	{	set;}
		
		Int32? Id	{	get;	set;}
		
		string FirstName	{	get;	set;}
		
		string LastName	{	get;	set;}
		
		string City	{	get;	set;}
		
		string Country	{	get;	set;}
		
		string Phone	{	get;	set;}
		
		Int32? CtrVersion	{	get;	}
		
		bool IsDirty	{	get;	set;}
		
		#endregion
	}
}
