/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using ProjectNameNorthwind.Data.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Business.Interfaces
{
	///<Summary>
	///Interface definition
	///This is the interface definition for the class BOOrderItem.
	///</Summary>
	public partial interface IBOOrderItem 
	{
		#region class methods
		
		///<Summary>
		///SaveNew
		///This method persists a new OrderItem record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void SaveNew();
		
		///<Summary>
		///Update
		///This method updates one OrderItem record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOOrderItem
		///</parameters>
		void Update();
		
		///<Summary>
		///Delete
		///This method deletes one OrderItem record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void Delete();
		
		#endregion

		#region member properties
		
		IOrderItemRepository OrderItemRepository	{	set;}
		
		Int32? Id	{	get;	set;}
		
		Int32? OrderId	{	get;	set;}
		
		Int32? ProductId	{	get;	set;}
		
		decimal? UnitPrice	{	get;	set;}
		
		Int32? Quantity	{	get;	set;}
		
		Int32? CtrVersion	{	get;	}
		
		bool IsDirty	{	get;	set;}
		
		#endregion
	}
}
