/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Collections.Generic;
using ProjectNameNorthwind.Data.Interfaces;
using ProjectNameNorthwind.Business.Repository.Interfaces;

namespace ProjectNameNorthwind.Business.Interfaces
{
	///<Summary>
	///Interface definition
	///This is the interface definition for the class BOSupplier.
	///</Summary>
	public partial interface IBOSupplier 
	{
		#region class methods
		
		///<Summary>
		///SaveNew
		///This method persists a new Supplier record to the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void SaveNew();
		
		///<Summary>
		///Update
		///This method updates one Supplier record in the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOSupplier
		///</parameters>
		void Update();
		
		///<Summary>
		///Delete
		///This method deletes one Supplier record from the store
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void Delete();
		
		///<Summary>
		///ProductCollection
		///This method returns its collection of BOProduct objects
		///</Summary>
		///<returns>
		///IList[IBOProduct]
		///</returns>
		///<parameters>
		///BOSupplier
		///</parameters>
		IList<IBOProduct> ProductCollection();
		
		///<Summary>
		///LoadProductCollection
		///This method loads the internal collection of BOProduct objects from storage. 
		///Call this if you need to ensure the collection is up-to-date (concurrency)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void LoadProductCollection();
		
		///<Summary>
		///AddProduct
		///This method persists a BOProduct object to the database collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///BOProduct
		///</parameters>
		void AddProduct(IBOProduct boProduct);
		
		///<Summary>
		///DeleteAllProduct
		///This method deletes all BOProduct objects from its collection
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		void DeleteAllProduct();
		
		#endregion

		#region member properties
		
		ISupplierRepository SupplierRepository	{	set;}
		
		IProductRepository ProductRepository	{	set;}
		
		Int32? Id	{	get;	set;}
		
		string CompanyName	{	get;	set;}
		
		string ContactName	{	get;	set;}
		
		string ContactTitle	{	get;	set;}
		
		string City	{	get;	set;}
		
		string Country	{	get;	set;}
		
		string Phone	{	get;	set;}
		
		string Fax	{	get;	set;}
		
		Int32? CtrVersion	{	get;	}
		
		bool IsDirty	{	get;	set;}
		
		#endregion
	}
}
