/*************************************************************
** Class generated by CodeTrigger, Version 6.1.0.7
** This class was generated on 5/6/2019 1:07:04 PM
** Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated
**************************************************************/
using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using ProjectNameNorthwind.Data.Interfaces;

namespace ProjectNameNorthwind.Data
{
	public partial class DAOProduct : BaseData, IDAOProduct
	{
		#region member variables
		protected Int32? _id;
		protected string _productName;
		protected Int32? _supplierId;
		protected decimal? _unitPrice;
		protected string _package;
		protected bool? _isDiscontinued;
		protected Int32? _ctrVersion;
		#endregion

		#region class methods
		public DAOProduct()
		{
		}
		///<Summary>
		///Select one row by primary key(s)
		///This method returns one row from the table Product based on the primary key(s)
		///</Summary>
		///<returns>
		///IDAOProduct
		///</returns>
		///<parameters>
		///Int32? id
		///</parameters>
		public static IDAOProduct SelectOne(Int32? id)
		{
			Doing(null);
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprProduct_SelectOne;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Product");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)id?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);
				Done(null);

				DAOProduct retObj = null;
				if(dt.Rows.Count > 0)
				{
					retObj = new DAOProduct();
					retObj._id					 = Convert.IsDBNull(dt.Rows[0]["Id"]) ? (Int32?)null : (Int32?)dt.Rows[0]["Id"];
					retObj._productName					 = Convert.IsDBNull(dt.Rows[0]["ProductName"]) ? null : (string)dt.Rows[0]["ProductName"];
					retObj._supplierId					 = Convert.IsDBNull(dt.Rows[0]["SupplierId"]) ? (Int32?)null : (Int32?)dt.Rows[0]["SupplierId"];
					retObj._unitPrice					 = Convert.IsDBNull(dt.Rows[0]["UnitPrice"]) ? (decimal?)null : (decimal?)dt.Rows[0]["UnitPrice"];
					retObj._package					 = Convert.IsDBNull(dt.Rows[0]["Package"]) ? null : (string)dt.Rows[0]["Package"];
					retObj._isDiscontinued					 = Convert.IsDBNull(dt.Rows[0]["IsDiscontinued"]) ? (bool?)null : (bool?)dt.Rows[0]["IsDiscontinued"];
					retObj._ctrVersion					 = Convert.IsDBNull(dt.Rows[0]["ctr_version"]) ? (Int32?)null : (Int32?)dt.Rows[0]["ctr_version"];
				}
				return retObj;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete one row by primary key(s)
		///this method allows the object to delete itself from the table Product based on its primary key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Delete()
		{
			Doing(this);
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprProduct_DeleteOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));

				command.ExecuteNonQuery();
				Done(this);

			}
			catch(Exception ex)
			{
				Failed(this, ex);
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by foreign key
		///This method returns all data rows in the table Product based on a foreign key
		///</Summary>
		///<returns>
		///IList-IDAOProduct.
		///</returns>
		///<parameters>
		///Int32? supplierId
		///</parameters>
		public static IList<IDAOProduct> SelectAllBySupplierId(Int32? supplierId)
		{
			Doing(null);
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprProduct_SelectAllBySupplierId;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Product");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@SupplierId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)supplierId?? (object)DBNull.Value));

				staticConnection.Open();
				sqlAdapter.Fill(dt);
				Done(null);

				List<IDAOProduct> objList = new List<IDAOProduct>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOProduct retObj = new DAOProduct();
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._productName					 = Convert.IsDBNull(row["ProductName"]) ? null : (string)row["ProductName"];
						retObj._supplierId					 = Convert.IsDBNull(row["SupplierId"]) ? (Int32?)null : (Int32?)row["SupplierId"];
						retObj._unitPrice					 = Convert.IsDBNull(row["UnitPrice"]) ? (decimal?)null : (decimal?)row["UnitPrice"];
						retObj._package					 = Convert.IsDBNull(row["Package"]) ? null : (string)row["Package"];
						retObj._isDiscontinued					 = Convert.IsDBNull(row["IsDiscontinued"]) ? (bool?)null : (bool?)row["IsDiscontinued"];
						retObj._ctrVersion					 = Convert.IsDBNull(row["ctr_version"]) ? (Int32?)null : (Int32?)row["ctr_version"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///Int32? supplierId
		///</parameters>
		public static Int32 SelectAllBySupplierIdCount(Int32? supplierId)
		{
			Doing(null);
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprProduct_SelectAllBySupplierIdCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@SupplierId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)supplierId?? (object)DBNull.Value));

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();
				Done(null);

				return retCount;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Delete all by foreign key
		///This method deletes all rows in the table Product with a given foreign key
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///IzProjectNameNorthwindConn_TxConnectionProvider connectionProvider, Int32? supplierId
		///</parameters>
		public static void DeleteAllBySupplierId(IConnectionProvider connectionProvider, Int32? supplierId)
		{
			Doing(null);
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprProduct_DeleteAllBySupplierId;
			command.CommandType = CommandType.Text;
			command.Connection = connectionProvider.Connection;
			command.Transaction = connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@SupplierId", SqlDbType.Int, 4, ParameterDirection.Input, false, 10, 0, "", DataRowVersion.Proposed, (object)supplierId?? (object)DBNull.Value));

				command.ExecuteNonQuery();
				Done(null);

			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Insert a new row
		///This method saves a new object to the table Product
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Insert()
		{
			Doing(this);
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprProduct_InsertOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _id));
				command.Parameters.Add(CtSqlParameter.Get("@ProductName", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_productName?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@SupplierId", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_supplierId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@UnitPrice", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 12, 2, "", DataRowVersion.Proposed, (object)_unitPrice?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Package", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_package?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@IsDiscontinued", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_isDiscontinued?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ctr_version", SqlDbType.Int, 4, ParameterDirection.Output, false, 10, 0, "", DataRowVersion.Proposed, _ctrVersion));

				command.ExecuteNonQuery();
				Done(this);

				_id					 = Convert.IsDBNull(command.Parameters["@Id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Id"].Value;
				_productName					 = Convert.IsDBNull(command.Parameters["@ProductName"].Value) ? null : (string)command.Parameters["@ProductName"].Value;
				_supplierId					 = Convert.IsDBNull(command.Parameters["@SupplierId"].Value) ? (Int32?)null : (Int32?)command.Parameters["@SupplierId"].Value;
				_unitPrice					 = Convert.IsDBNull(command.Parameters["@UnitPrice"].Value) ? (decimal?)null : (decimal?)command.Parameters["@UnitPrice"].Value;
				_package					 = Convert.IsDBNull(command.Parameters["@Package"].Value) ? null : (string)command.Parameters["@Package"].Value;
				_isDiscontinued					 = Convert.IsDBNull(command.Parameters["@IsDiscontinued"].Value) ? (bool?)null : (bool?)command.Parameters["@IsDiscontinued"].Value;
				_ctrVersion					 = Convert.IsDBNull(command.Parameters["@ctr_version"].Value) ? (Int32?)null : (Int32?)command.Parameters["@ctr_version"].Value;

			}
			catch(Exception ex)
			{
				Failed(this, ex);
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows
		///This method returns all data rows in the table Product
		///</Summary>
		///<returns>
		///IList-IDAOProduct.
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static IList<IDAOProduct> SelectAll()
		{
			Doing(null);
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprProduct_SelectAll;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Product");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				staticConnection.Open();
				sqlAdapter.Fill(dt);
				Done(null);

				List<IDAOProduct> objList = new List<IDAOProduct>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOProduct retObj = new DAOProduct();
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._productName					 = Convert.IsDBNull(row["ProductName"]) ? null : (string)row["ProductName"];
						retObj._supplierId					 = Convert.IsDBNull(row["SupplierId"]) ? (Int32?)null : (Int32?)row["SupplierId"];
						retObj._unitPrice					 = Convert.IsDBNull(row["UnitPrice"]) ? (decimal?)null : (decimal?)row["UnitPrice"];
						retObj._package					 = Convert.IsDBNull(row["Package"]) ? null : (string)row["Package"];
						retObj._isDiscontinued					 = Convert.IsDBNull(row["IsDiscontinued"]) ? (bool?)null : (bool?)row["IsDiscontinued"];
						retObj._ctrVersion					 = Convert.IsDBNull(row["ctr_version"]) ? (Int32?)null : (Int32?)row["ctr_version"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///
		///</parameters>
		public static Int32 SelectAllCount()
		{
			Doing(null);
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprProduct_SelectAllCount;
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();
				Done(null);

				return retCount;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select specific fields of all rows using criteriaquery api
		///This method returns specific fields of all data rows in the table using criteriaquery apiProduct
		///</Summary>
		///<returns>
		///IDictionary-string, IList-object..
		///</returns>
		///<parameters>
		///IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IDictionary<string, IList<object>> SelectAllByCriteriaProjection(IList<IDataProjection> listProjection, IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			Doing(null);
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprProduct_SelectAllByCriteriaProjection, listProjection, listCriterion, listOrder, dataSkip, dataTake);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Product");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				staticConnection.Open();
				sqlAdapter.Fill(dt);
				Done(null);

				IDictionary<string, IList<object>> dict = new Dictionary<string, IList<object>>();
				foreach (IDataProjection projection in listProjection)
				{
					IList<object> lst = new List<object>();
					dict.Add(projection.Member, lst);
					foreach (DataRow row in dt.Rows)
					{
						if (string.Compare(projection.Member, "Id", true) == 0) lst.Add(Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"]);
						if (string.Compare(projection.Member, "ProductName", true) == 0) lst.Add(Convert.IsDBNull(row["ProductName"]) ? null : (string)row["ProductName"]);
						if (string.Compare(projection.Member, "SupplierId", true) == 0) lst.Add(Convert.IsDBNull(row["SupplierId"]) ? (Int32?)null : (Int32?)row["SupplierId"]);
						if (string.Compare(projection.Member, "UnitPrice", true) == 0) lst.Add(Convert.IsDBNull(row["UnitPrice"]) ? (decimal?)null : (decimal?)row["UnitPrice"]);
						if (string.Compare(projection.Member, "Package", true) == 0) lst.Add(Convert.IsDBNull(row["Package"]) ? null : (string)row["Package"]);
						if (string.Compare(projection.Member, "IsDiscontinued", true) == 0) lst.Add(Convert.IsDBNull(row["IsDiscontinued"]) ? (bool?)null : (bool?)row["IsDiscontinued"]);
					}
				}
				return dict;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select all rows by filter criteria
		///This method returns all data rows in the table using criteriaquery api Product
		///</Summary>
		///<returns>
		///IList-IDAOProduct.
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake
		///</parameters>
		public static IList<IDAOProduct> SelectAllByCriteria(IList<IDataCriterion> listCriterion, IList<IDataOrderBy> listOrder, IDataSkip dataSkip, IDataTake dataTake)
		{
			Doing(null);
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprProduct_SelectAllByCriteria, null, listCriterion, listOrder, dataSkip, dataTake);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			DataTable dt = new DataTable("Product");
			SqlDataAdapter sqlAdapter = new SqlDataAdapter(command);
			try
			{

				staticConnection.Open();
				sqlAdapter.Fill(dt);
				Done(null);

				List<IDAOProduct> objList = new List<IDAOProduct>();
				if(dt.Rows.Count > 0)
				{
					foreach(DataRow row in dt.Rows)
					{
						DAOProduct retObj = new DAOProduct();
						retObj._id					 = Convert.IsDBNull(row["Id"]) ? (Int32?)null : (Int32?)row["Id"];
						retObj._productName					 = Convert.IsDBNull(row["ProductName"]) ? null : (string)row["ProductName"];
						retObj._supplierId					 = Convert.IsDBNull(row["SupplierId"]) ? (Int32?)null : (Int32?)row["SupplierId"];
						retObj._unitPrice					 = Convert.IsDBNull(row["UnitPrice"]) ? (decimal?)null : (decimal?)row["UnitPrice"];
						retObj._package					 = Convert.IsDBNull(row["Package"]) ? null : (string)row["Package"];
						retObj._isDiscontinued					 = Convert.IsDBNull(row["IsDiscontinued"]) ? (bool?)null : (bool?)row["IsDiscontinued"];
						retObj._ctrVersion					 = Convert.IsDBNull(row["ctr_version"]) ? (Int32?)null : (Int32?)row["ctr_version"];
						objList.Add(retObj);
					}
				}
				return objList;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return null;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Select count of all rows using criteriaquery api
		///This method returns all data rows in the table using criteriaquery api Product
		///</Summary>
		///<returns>
		///Int32
		///</returns>
		///<parameters>
		///IList<IDataCriterion> listCriterion
		///</parameters>
		public static Int32 SelectAllByCriteriaCount(IList<IDataCriterion> listCriterion)
		{
			Doing(null);
			SqlCommand	command = new SqlCommand();
			command.CommandText = GetSelectionCriteria(InlineProcs.ctprProduct_SelectAllByCriteriaCount, null, listCriterion, null);
			command.CommandType = CommandType.Text;
			SqlConnection staticConnection = StaticSqlConnection;
			command.Connection = staticConnection;

			try
			{

				staticConnection.Open();
				Int32 retCount = (Int32)command.ExecuteScalar();
				Done(null);

				return retCount;
			}
			catch(Exception ex)
			{
				Failed(null, ex);
				Handle(null, ex);
				return -1;
			}
			finally
			{
				staticConnection.Close();
				command.Dispose();
			}
		}

		///<Summary>
		///Update one row by primary key(s)
		///This method allows the object to update itself in the table Product based on its primary key(s)
		///</Summary>
		///<returns>
		///void
		///</returns>
		///<parameters>
		///
		///</parameters>
		public virtual void Update()
		{
			Doing(this);
			SqlCommand	command = new SqlCommand();
			command.CommandText = InlineProcs.ctprProduct_UpdateOne;
			command.CommandType = CommandType.Text;
			command.Connection = _connectionProvider.Connection;
			command.Transaction = _connectionProvider.CurrentTransaction;

			try
			{
				command.Parameters.Add(CtSqlParameter.Get("@Id", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_id?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ProductName", SqlDbType.NVarChar, 50, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_productName?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@SupplierId", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_supplierId?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@UnitPrice", SqlDbType.Decimal, 9, ParameterDirection.InputOutput, true, 12, 2, "", DataRowVersion.Proposed, (object)_unitPrice?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@Package", SqlDbType.NVarChar, 30, ParameterDirection.InputOutput, true, 0, 0, "", DataRowVersion.Proposed, (object)_package?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@IsDiscontinued", SqlDbType.Bit, 1, ParameterDirection.InputOutput, false, 0, 0, "", DataRowVersion.Proposed, (object)_isDiscontinued?? (object)DBNull.Value));
				command.Parameters.Add(CtSqlParameter.Get("@ctr_version", SqlDbType.Int, 4, ParameterDirection.InputOutput, false, 10, 0, "", DataRowVersion.Proposed, (object)_ctrVersion?? (object)DBNull.Value));

				command.ExecuteNonQuery();
				Done(this);

				_id					 = Convert.IsDBNull(command.Parameters["@Id"].Value) ? (Int32?)null : (Int32?)command.Parameters["@Id"].Value;
				_productName					 = Convert.IsDBNull(command.Parameters["@ProductName"].Value) ? null : (string)command.Parameters["@ProductName"].Value;
				_supplierId					 = Convert.IsDBNull(command.Parameters["@SupplierId"].Value) ? (Int32?)null : (Int32?)command.Parameters["@SupplierId"].Value;
				_unitPrice					 = Convert.IsDBNull(command.Parameters["@UnitPrice"].Value) ? (decimal?)null : (decimal?)command.Parameters["@UnitPrice"].Value;
				_package					 = Convert.IsDBNull(command.Parameters["@Package"].Value) ? null : (string)command.Parameters["@Package"].Value;
				_isDiscontinued					 = Convert.IsDBNull(command.Parameters["@IsDiscontinued"].Value) ? (bool?)null : (bool?)command.Parameters["@IsDiscontinued"].Value;
				_ctrVersion					 = Convert.IsDBNull(command.Parameters["@ctr_version"].Value) ? (Int32?)null : (Int32?)command.Parameters["@ctr_version"].Value;

			}
			catch(Exception ex)
			{
				Failed(this, ex);
				Handle(this, ex);
			}
			finally
			{
				command.Dispose();
			}
		}

		#endregion

		#region member properties

		public Int32? Id
		{
			get
			{
				return _id;
			}
			set
			{
				_id = value;
			}
		}

		public string ProductName
		{
			get
			{
				return _productName;
			}
			set
			{
				_productName = value;
			}
		}

		public Int32? SupplierId
		{
			get
			{
				return _supplierId;
			}
			set
			{
				_supplierId = value;
			}
		}

		public decimal? UnitPrice
		{
			get
			{
				return _unitPrice;
			}
			set
			{
				_unitPrice = value;
			}
		}

		public string Package
		{
			get
			{
				return _package;
			}
			set
			{
				_package = value;
			}
		}

		public bool? IsDiscontinued
		{
			get
			{
				return _isDiscontinued;
			}
			set
			{
				_isDiscontinued = value;
			}
		}

		public Int32? CtrVersion
		{
			get
			{
				return _ctrVersion;
			}
			set
			{
				_ctrVersion = value;
			}
		}

		#endregion
	}
}

#region inline sql procs
namespace ProjectNameNorthwind.Data
{
	public partial class InlineProcs
	{
		internal static string ctprProduct_SelectOne = @"
			-- Select one row based on the primary key(s)
			-- selects all rows from the table
			SELECT 
			[Id]
			,[ProductName]
			,[SupplierId]
			,[UnitPrice]
			,[Package]
			,[IsDiscontinued]
			,[ctr_version]
			FROM [dbo].[Product]
			WHERE 
			[Id] = @Id
			";

		internal static string ctprProduct_DeleteOne = @"
			-- Delete a row based on the primary key(s)
			-- delete all matching from the table
			DELETE [dbo].[Product]
			WHERE 
			[Id] = @Id
			";

		internal static string ctprProduct_SelectAllBySupplierId = @"
			-- Select all rows based on a foreign key
			-- selects all rows from the table
			SELECT 
			[Id]
			,[ProductName]
			,[SupplierId]
			,[UnitPrice]
			,[Package]
			,[IsDiscontinued]
			,[ctr_version]
			FROM [dbo].[Product]
			WHERE 
			[SupplierId] = @SupplierId OR ([SupplierId] IS NULL AND @SupplierId IS NULL)
			";

		internal static string ctprProduct_SelectAllBySupplierIdCount = @"
			-- Get count of rows returnable by this query
			-- selects count of all rows from the table
			SELECT COUNT(*)
			FROM [dbo].[Product]
			WHERE 
			[SupplierId] = @SupplierId OR ([SupplierId] IS NULL AND @SupplierId IS NULL)
			";

		internal static string ctprProduct_DeleteAllBySupplierId = @"
			
			-- delete all matching from the table
			DELETE [dbo].[Product]
			WHERE 
			[SupplierId] = @SupplierId OR ([SupplierId] IS NULL AND @SupplierId IS NULL)
			";

		internal static string ctprProduct_InsertOne = @"
			-- Insert a new row
			-- inserts a new row into the table
			INSERT [dbo].[Product]
			(
			[ProductName]
			,[SupplierId]
			,[UnitPrice]
			,[Package]
			,[IsDiscontinued]
			)
			VALUES
			(
			@ProductName
			,@SupplierId
			,@UnitPrice
			,@Package
			,@IsDiscontinued
			)
			SELECT 
			@Id = [Id]
			,@ProductName = [ProductName]
			,@SupplierId = [SupplierId]
			,@UnitPrice = [UnitPrice]
			,@Package = [Package]
			,@IsDiscontinued = [IsDiscontinued]
			,@ctr_version = [ctr_version]
			FROM [dbo].[Product]
			WHERE 
			[Id] = SCOPE_IDENTITY()
			";

		internal static string ctprProduct_SelectAll = @"
			-- Select All rows
			-- selects all rows from the table
			SELECT 
			[Id]
			,[ProductName]
			,[SupplierId]
			,[UnitPrice]
			,[Package]
			,[IsDiscontinued]
			,[ctr_version]
			FROM [dbo].[Product]
			";

		internal static string ctprProduct_SelectAllCount = @"
			
			-- selects count of all rows from the table
			SELECT COUNT(*)
			FROM [dbo].[Product]
			";

		internal static string ctprProduct_SelectAllByCriteriaProjection = @"
			
			-- selects all rows from the table by criteria
			SELECT 
			##STARTFIELDS##
			##ENDFIELDS##
			FROM [dbo].[Product]
			##CRITERIA##
			";

		internal static string ctprProduct_SelectAllByCriteria = @"
			
			-- selects all rows from the table by criteria
			SELECT 
			[Id]
			,[ProductName]
			,[SupplierId]
			,[UnitPrice]
			,[Package]
			,[IsDiscontinued]
			,[ctr_version]
			FROM [dbo].[Product]
			##CRITERIA##
			";

		internal static string ctprProduct_SelectAllByCriteriaCount = @"
			
			-- selects count of all rows from the table according to criteria
			SELECT COUNT(*)
			FROM [dbo].[Product]
			##CRITERIA##
			";

		internal static string ctprProduct_UpdateOne = @"
			-- Update one row based on the primary key(s)
			-- updates a row in the table based on the primary key
			
			--data optimistic concurrency handling ----------------------------
			DECLARE @currVersion INT
			SELECT @currVersion = [ctr_version] FROM [dbo].[Product]
			WHERE [Id] = @Id
			
			IF @currVersion > @ctr_version
			RAISERROR('data concurrency issue updating this record, possible stale data. %s', 16, 1, 
			'[dbo].[Product] WHERE WHERE [Id] = @Id')
			
			IF @currVersion IS NULL
			RAISERROR('data concurrency issue updating this record, record not available (not found). %s', 16, 1, 
			'[dbo].[Product] WHERE WHERE [Id] = @Id')
			
			SET @ctr_version = @currVersion  + 1 
			-------------------------------------------------------------------
			UPDATE [dbo].[Product]
			SET
			[ProductName] = @ProductName
			,[SupplierId] = @SupplierId
			,[UnitPrice] = @UnitPrice
			,[Package] = @Package
			,[IsDiscontinued] = @IsDiscontinued
			,[ctr_version] = @ctr_version
			WHERE 
			[Id] = @Id
			SELECT 
			@Id = [Id]
			,@ProductName = [ProductName]
			,@SupplierId = [SupplierId]
			,@UnitPrice = [UnitPrice]
			,@Package = [Package]
			,@IsDiscontinued = [IsDiscontinued]
			,@ctr_version = [ctr_version]
			FROM [dbo].[Product]
			WHERE 
			[Id] = @Id
			";

	}
}
#endregion
